# Generated by Django 2.1.2 on 2018-12-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nathanoluwaseyiscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumyuser',
            options={'ordering': ['nickname']},
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
