# Generated by Django 2.1.2 on 2018-12-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nathanoluwaseyiscrumy', '0002_auto_20181213_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalstatus',
            options={'ordering': ['-id']},
        ),
    ]
