# Generated by Django 2.1.2 on 2018-12-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nathanoluwaseyiscrumy', '0003_auto_20181213_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumyuser',
            name='age',
        ),
    ]
